// SPDX-License-Identifier: AGPL-3.0-only
package main

import (
	"log"
	"net/http"
	"os"

	"zxy-panel/backend/internal/api"
	"zxy-panel/backend/internal/store"
	appversion "zxy-panel/backend/internal/version"
)

func main() {
	addr := getenv("ZXY_API_ADDR", "0.0.0.0:8088")
	dbPath := getenv("ZXY_DB_PATH", "./data/zxy-panel.json")
	s, err := store.Open(dbPath)
	if err != nil {
		log.Fatal(err)
	}
	handler := api.NewRouter(s)
	log.Printf("ZXY Panel API %s listening on http://%s", appversion.Version, addr)
	log.Printf("data file: %s", dbPath)
	log.Printf("default admin is generated by installer, please change after first login")
	if err := http.ListenAndServe(addr, handler); err != nil {
		log.Fatal(err)
	}
}
func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
